# Generated by Django 4.2.1 on 2023-05-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_interests_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'managed': True, 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='interest',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='interest',
            table='db_interests',
        ),
    ]
