# Generated by Django 4.2.1 on 2023-05-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_interest_options_rename_interest_interest_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'managed': True, 'verbose_name': 'Interest', 'verbose_name_plural': 'Interests'},
        ),
    ]
