# Generated by Django 4.2.1 on 2023-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_interest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True, 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='db_profiles',
        ),
    ]
